### ISSUE TITLE
scanning with clamav file stored from API

### ISSUE THREAD

**Issue by SnakeByteIL** [botherder/viper#146]
clamav
gives the error:
[!] Check permissions of the binary folder, Can't open file or directory

binary folder permissions seems to be ok, even changed to 777 and still same error. 

This only happens if the file was submitted via the api.py

**Comment by megamatman** [comment]
This is most likely a permissions issue with clamav.  Are you running api.py as root? Potentially the permissions of the associated binaries directory are messed up because of that.

Try:
ls -l /your/path/here/binaries/

Who is the owner? Root?

If so, you could try:
sudo chmod -R o+rx /your/path/here/binaries/

**Comment by neriberto** [comment]
Hi, 

Check this link : http://superuser.com/questions/671116/why-clamav-cant-scan-some-files I think can be the apparmor,... here I store my samples in /opt/viper/binaries, then I just added :

```
/opt/** r,
```

in /etc/apparmor.d/local/usr.sbin.clamd and resolved

**Comment by SnakeByteIL** [comment]
still having this problem the app armor addition did not solve this

**Comment by megamatman** [comment]
@SnakeByteIL did you check the permissions?

**Comment by SnakeByteIL** [comment]
yep all in order...

**Comment by megamatman** [comment]
@SnakeByteIL Puzzling.... I'd be interested to see the output of the ls -l of your Viper projects directory

**Comment by SnakeByteIL** [comment]
Not working from "projects" using just the main.
Everything stored under Binaries with "drwxrwxrwx" permission. 
still clam can't access it

**Comment by SnakeByteIL** [comment]
after re-testing @neriberto solution's seems to solve this.
