### ISSUE TITLE
tags -d removes all tags of that name

### ISSUE THREAD

**Issue by kevthehermit** [botherder/viper#156]
You cant remove a tag from single files. tags -d removes the tag from all files.

**Comment by botherder** [comment]
Any update on this?

**Comment by botherder** [comment]
This and #210 are the only two tickets open for 1.2, and they are somewhat related. I was understanding that @kevthehermit was working on them. Do we have an estimated time for completion?

**Comment by botherder** [comment]
Fixed in 20f6de5ea3ba2ec2065e1a7b309c8b2bbbe5bd2b.
