### ISSUE TITLE
Idea: "cat"-like output web/CL

### ISSUE THREAD

**Issue by deralexxx** [botherder/viper#190]
I was wondering if anyone else ever felt the need for a simple output of sourcecode of a file via CL / Web.

Of course you can go for cat $file, but maybe it would be handy to just explore a file.

What is the community opinion on that?

**Comment by botherder** [comment]
I'm not sure what you mean. You can do all sorts from the command line using ! prefix and on the web interface there is the hex view.

**Comment by deralexxx** [comment]
Ok, haven't seen the hex view in web, was running a web version without hex view.

And I just learned about the "!", do we expect users to know that or shall we document it somewhere in the help page?
