### ISSUE TITLE
Issue with Debup -s

### ISSUE THREAD

**Issue by JuTz0r** [botherder/viper#197]
The file in question is a BUP file and was working with v1.1 release on the website

Issue
CLI:
Malware viper 7dd717a301e3d80.bup > debup -s
[*] Session opened on /tmp/A0712038.EXE
[*] Switching Session to Embedded File
[!] Not a valid BUP File
Malware viper A0712038.EXE >

This works but it's still returning the error.

Web:
Switching Session to Embedded File
Not a valid BUP File

This does not switch to the extracted file and only returns erros

**Comment by kevthehermit** [comment]
I will have a look tonight, Do you mind sharing the BUP file so i can test?

**Comment by JuTz0r** [comment]
Sure thing,  any place in particular you want it sent?

**Comment by kevthehermit** [comment]
http://viper.malwareconfig.com/ Just upload it there :)

**Comment by JuTz0r** [comment]
Its up there, but that version seemed to work, vs the latest pull

**Comment by kevthehermit** [comment]
Thanks. Thats a modified version i run. I found the issue and will push a fix up tonight, Im just finishing mods to the documentation first

**Comment by kevthehermit** [comment]
Fixed with https://github.com/botherder/viper/pull/199

Rewrites the Bup module to fix an error and switch from the old OleFile_PL to the new olefile

requires ``pip install olefile``. this has been added to the requirement.txt file already. and the module shoudl warn you
