### ISSUE TITLE
add 'swig' to requriments 

### ISSUE THREAD

**Issue by SnakeByteIL** [botherder/viper#204]
should 'swig' be add to requirements installation list since 'M2Crypto' needs it to be installed?

**Comment by botherder** [comment]
Doesn't pip resolve it itself when doing pip install?

**Comment by SnakeByteIL** [comment]
not that I know of.
Happened on another instance today. 

Also libssl-dev was asked to be installed as well. 

its on linux ubuntu 14.04

**Comment by kevthehermit** [comment]
Confirming this is an issue, clean install of Ubuntu 14.04

requirements install fails at M2Crypto

An ```apt-get install libssl-dev swig``` is required to make this work.

**Comment by botherder** [comment]
That sucks. I guess either we document this or try to get rid of M2Crypto.
