### ISSUE TITLE
web.py don't really delete tags

### ISSUE THREAD

**Issue by SnakeByteIL** [botherder/viper#210]
when clicking on delete tags it just move to the following url:
/tags?action=delete&value=TestTag

https://github.com/botherder/viper/blob/master/web.py#L442 

maybe we should change this to return error of something like "this is not implemented yet" ?

**Comment by kevthehermit** [comment]
This is next on my list to look at a way to remove individual tags from the DB,

**Comment by SnakeByteIL** [comment]
Want me to do a little "patch" mean while?

**Comment by botherder** [comment]
Any update on this?

**Comment by botherder** [comment]
Fixed with 15ead6c5dbbfadae3422d38344cab26b266265b6.
