### ISSUE TITLE
New Module: "macho"

### ISSUE THREAD

**Issue by deralexxx** [botherder/viper#219]
Would like to get feedback for a new module "macho" before doing a pull request.

The idea is to get info for mac files.
The module is based on: https://github.com/thetlk/Mach-O

Format reference:
https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachORuntime/index.html

Example with https://github.com/thetlk/Mach-O/blob/master/sample/bin-ls-x86_64::
 
![1](https://cloud.githubusercontent.com/assets/741037/5957557/4ae0aaea-a7bb-11e4-8b4a-e85ea8438344.png)

    
help:
 
![2](https://cloud.githubusercontent.com/assets/741037/5957563/652a4104-a7bb-11e4-9a75-34be65a29941.png)

Header:
![3](https://cloud.githubusercontent.com/assets/741037/5957604/c7d10d88-a7bb-11e4-8aec-003e6f27573d.png)

Segments:
![4](https://cloud.githubusercontent.com/assets/741037/5957595/b5560e9c-a7bb-11e4-8492-11dc1825ecf3.png)

Commands:
![5](https://cloud.githubusercontent.com/assets/741037/5957598/bb957b08-a7bb-11e4-9333-9b8cbbe320ee.png)

It can be found:
https://github.com/deralexxx/viper/tree/new_module_macho

I would be happy to make a pull request, thoughts?

**Comment by SnakeByteIL** [comment]
Didn't test it yet but maybe it should go as a "sub-module" 

something like $ OSX macho args ? 

If viper will have more OSX specific command it might start to get confusing ?

**Comment by botherder** [comment]
I think it's alright. We have the same thing for PE and ELF files.
If you want to make a pull request, please go ahead.
