### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by nietzfock** [botherder/viper#223]
I do not know why it gives this error.
myproyecto viper calc.exe > yara scan
[!] The command yara raised an exception:
Traceback (most recent call last):
  File "/opt/viper/viper/core/ui/console.py", line 257, in start
    module.run()
  File "/opt/viper/modules/yarascan.py", line 191, in run
    self.scan()
  File "/opt/viper/modules/yarascan.py", line 82, in scan
    rules = yara.compile(arg_rule)
  File "/usr/local/lib/python2.7/dist-packages/yara/rules.py", line 464, in compile
    rules = Rules(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yara/rules.py", line 226, in __init__
    string = preprocess(path, defines, include_path)
  File "/usr/local/lib/python2.7/dist-packages/yara/preprocessor.py", line 69, in preprocess
    _process(infile, output, copy.copy(defines), include_paths, paths)
  File "/usr/local/lib/python2.7/dist-packages/yara/preprocessor.py", line 128, in _process
    raise PreprocessError(msg, defines)
PreprocessError: data/yara/index.yara:0:Invalid file extension '.yara'.Can only include .yar

**Comment by r3comp1le** [comment]
u check that last line?  index.yara vs index.yar

**Comment by nietzfock** [comment]
I do not know where he gets the directory
myproyecto viper calc.exe > yara rules
+----+-----------------------------------+
| #  | Path                              |
+----+-----------------------------------+
| 1  | data/yara/GeorBotBinary.yara      |
| 2  | data/yara/fpu.yara                |
| 3  | data/yara/vmdetect.yara           |
| 4  | data/yara/embedded.yara           |
| 5  | data/yara/GeorBotMemory.yara      |
| 6  | data/yara/citizenlab.yara         |
| 7  | data/yara/apt1.yara               |
| 8  | data/yara/hangover.yara           |
| 9  | data/yara/index.yara              |
| 10 | data/yara/leverage.yar            |
| 11 | data/yara/rats.yara               |
| 12 | data/yara/APT_NGO_wuaclt_PDF.yara |
| 13 | data/yara/urausy_skypedat.yar     |
| 14 | data/yara/themask.yara            |
| 15 | data/yara/kins.yara               |

**Comment by nietzfock** [comment]
https://github.com/botherder/viper/issues/82

**Comment by kevthehermit** [comment]
Did you check for the answer in issue 82? 
What version of Yara are you running?
Did you install yara-python from pip or did you install from the yara tarball?

**Comment by nietzfock** [comment]
/usr/lib/python2.7/dist-packages# yara -version
yara 2.1


not remember where download  yara-python
/Downloads/yara-python-1.7# python setup.py build
running build
running build_ext
building 'yara' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c yara-python.c -o build/temp.linux-i686-2.7/yara-python.o
creating build/lib.linux-i686-2.7
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-i686-2.7/yara-python.o -lyara -lpcre -o build/lib.linux-i686-2.7/yara.so
root@kali:~/Downloads/yara-python-1.7# python setup.py install
running install
running build
running build_ext
running install_lib
copying build/lib.linux-i686-2.7/yara.so -> /usr/local/lib/python2.7/dist-packages
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/yara_python-1.7.egg-info

**Comment by aschuster99** [comment]
You are using yara v2.1, but v1.7 of the bindings. That might be the problem.

**Comment by botherder** [comment]
Besides, Yara is at 3.2.0 now.
