### ISSUE TITLE
clamav scan fails with [!] Check permissions of the binary folder, lstat() failed: Permission denied.

### ISSUE THREAD

**Issue by andyrat33** [botherder/viper#252]
dionaea viper c03ac6aa836bad949bc531bcd60aaf99 > clamav
[!] Check permissions of the binary folder, lstat() failed: Permission denied.

clamdscan fails outside of viper with the same error:
-rw-rw-r-- 1 andy andy 162472 Mar 28 21:15 4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b
andy@docker1:~/viper$ clamdscan projects/dionaea/binaries/
/home/andy/viper/projects/dionaea/binaries: lstat() failed: Permission denied. ERROR
Time: 0.000 sec (0 m 0 s)

Looking at the source files it seems clamdscan needs rx for everyone on a file:
clamdscan c03ac6aa836bad949bc531bcd60aaf99
/home/andy/dionaea/binaries/c03ac6aa836bad949bc531bcd60aaf99: Access denied. ERROR

andy@docker1:~/dionaea/binaries$ ls -l  c03ac6aa836bad949bc531bcd60aaf99
-rw------- 1 andy andy 170505 Feb 28 19:56 c03ac6aa836bad949bc531bcd60aaf99

andy@docker1:~/dionaea/binaries$ chmod 755 c03ac6aa836bad949bc531bcd60aaf99
andy@docker1:~/dionaea/binaries$ ls -l c03ac6aa836bad949bc531bcd60aaf99
-rwxr-xr-x 1 andy andy 170505 Feb 28 19:56 c03ac6aa836bad949bc531bcd60aaf99
andy@docker1:~/dionaea/binaries$ clamdscan c03ac6aa836bad949bc531bcd60aaf99
/home/andy/dionaea/binaries/c03ac6aa836bad949bc531bcd60aaf99: Worm.Kido-299 FOUND

----------- SCAN SUMMARY -----------
Infected files: 1
Time: 0.029 sec (0 m 0 s)

However the same fix does not work for files in the project repository:
andy@docker1:~/viper/projects/dionaea$ clamdscan /home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b
/home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b: lstat() failed: Permission denied. ERROR

----------- SCAN SUMMARY -----------
Infected files: 0
Total errors: 1
Time: 0.000 sec (0 m 0 s)
andy@docker1:~/viper/projects/dionaea$ chmod 755 /home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b
andy@docker1:~/viper/projects/dionaea$ clamdscan /home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b
/home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b: lstat() failed: Permission denied. ERROR

----------- SCAN SUMMARY -----------
Infected files: 0
Total errors: 1
Time: 0.000 sec (0 m 0 s)
andy@docker1:~/viper/projects/dionaea$ ls -l /home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b
-rwxr-xr-x 1 andy andy 170505 Mar 28 21:15 /home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b

I would conclude that it seems like its the length of the filename passed to clamdscan that it does not like. 

OS: Ubuntu 14.04 LTS

**Comment by andyrat33** [comment]
It seems like filename length
andy@docker1:~/viper/projects/dionaea$ cp /home/andy/viper/projects/dionaea/binaries/4/a/3/2/4a32c8effab60ed432762d13c0087eb7816c760fc7e2daaf9eb423774e23701b /home/andy/test-4a32c8e
andy@docker1:~/viper/projects/dionaea$ cd
andy@docker1:~$ clamdscan /home/andy/test-4a32c8e
/home/andy/test-4a32c8e: Worm.Kido-299 FOUND

----------- SCAN SUMMARY -----------
Infected files: 1
Time: 0.033 sec (0 m 0 s)
Messing about with chmod shows the file just needs read for everyone for clamdscan to work
-r-x---r-- 1 andy andy 170505 Mar 29 09:45 /home/andy/test-4a32c8e
andy@docker1:~$ clamdscan /home/andy/test-4a32c8e
/home/andy/test-4a32c8e: Worm.Kido-299 FOUND

----------- SCAN SUMMARY -----------
Infected files: 1
Time: 0.029 sec (0 m 0 s)

**Comment by botherder** [comment]
I presume this is not a Viper issue then, but a ClamScan issue instead. Can we close this ticket?

**Comment by andyrat33** [comment]
Yes, that's true, but I expect others will find the same problem and may look here too. I have posted a bug on the clamav bugzilla. hopefully will get fixed :-)

**Comment by botherder** [comment]
Very good, thanks.
