### ISSUE TITLE
Documentation for 1.2

### ISSUE THREAD

**Issue by deralexxx** [botherder/viper#260]
Would like to know if there are things that needs to be documented for v1.2.

Special modules?

Do we want to have a "known issues" section?

**Comment by botherder** [comment]
The documentation doesn't contain information on modules, cause as we expected more to come (although we didn't really get that many more) it would have become really tedious to document them all and keep it up to date.

A Known Issues section could be good I guess.

**Comment by deralexxx** [comment]
already merged
