### ISSUE TITLE
update.py 1.1 --> 1.2 fails

### ISSUE THREAD

**Issue by deralexxx** [botherder/viper#268]
I got this error:

    python update.py 
    [!] WARNING: If you proceed you will lose any changes you might have made to Viper.
    Are you sure you want to proceed? [y/N] y
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method     Magic.__del__ of <magic.Magic object at 0x103989290>> ignored
    [*] .gitignore up-to-date
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method     Magic.__del__ of <magic.Magic object at 0x102f00b90>> ignored
    [+] File .travis.yml has been updated
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method     Magic.__del__ of <magic.Magic object at 0x102f00b90>> ignored
    [+] File CHANGELOG has been updated
    [+] New file CONTRIBUTING.md has been created
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method     Magic.__del__ of <magic.Magic object at 0x102f00b90>> ignored
    [+] File LICENSE has been updated
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method     Magic.__del__ of <magic.Magic object at 0x102f00b90>> ignored
    [+] File README.md has been updated
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method Magic.__del__ of <magic.Magic object at 0x102f00b90>> ignored
    [+] File api.py has been updated
    Exception AttributeError: AttributeError("'Magic' object has no attribute 'cookie'",) in <bound method     Magic.__del__ of <magic.Magic object at 0x102f00a50>> ignored
    [*] data/peid/UserDB.TXT up-to-date
    Traceback (most recent call last):
      File "update.py", line 79, in <module>
        main()
      File "update.py", line 66, in main
        new_local = open(local_file_path, 'w')
    IOError: [Errno 2] No such file or directory: 'data/web/'

**Comment by botherder** [comment]
Closing as it's already addressed in 1.2.
