### ISSUE TITLE
oletools.olevba missing

### ISSUE THREAD

**Issue by shibumi** [botherder/viper#271]
Hello,
I get while starting viper the following message:

[!] Something wrong happened while importing the module modules.office: No module named oletools.olevba

python2-olefile is installed..

**Comment by kevthehermit** [comment]
you need the latest oletools and olefile from pip.

pip install -r requirements.txt should do this for you.

**Comment by shibumi** [comment]
I have python2-olefile installed:

**Comment by kevthehermit** [comment]
you need 
olefile - http://www.decalage.info/olefile

AND 

oletools - http://www.decalage.info/python/oletools

They are two separate libraries

**Comment by decalage2** [comment]
Actually oletools contains its own copy of olefile (that I maintain up-to-date whenever I release a new olefile version), so you could remove the dependency on olefile, and keep only oletools to simplify things. 
In that case, "import olefile" should be changed to "import oletools.thirdparty.olefile as olefile".

**Comment by shibumi** [comment]
the issue is fixed for me thx guys. I close the issue..
