### ISSUE TITLE
Tags command doesn't raise an error when the file is not stored

### ISSUE THREAD

**Issue by botherder** [botherder/viper#273]
If a user tries to add tags to a file which is not stored, the tags command currently doesn't display any error. This is a corner case, as normally a user should understand the mechanics of Viper storage and repository, but a better error handling is required.

**Comment by SnakeByteIL** [comment]
I wonder why not automatically storing every new file?

**Comment by botherder** [comment]
Cause I don't want to pollute my projects or repositories with files I'm inspecting and turn out to not be interesting. Also, sessions are used for temporary analysis of files and binary data extracted through other modules (like PE32 resources, email attachments and what not).
If we were to automatically store every file, the repository would be complete mess.

**Comment by botherder** [comment]
Fixed with 1d4273f.
